[package]
name = "celma_lang_v1"
version = "0.1.0"
authors = ["d-plaindoux <d.plaindoux@free.fr>"]
edition = "2021"

[dependencies]
celma_core = { version = "0.1.0", path = "../core" }
# celma_lang = { version = "0.1.0", path = "../lang" }
celma_macro = { version = "0.1.0", path = "../macro" }
