[package]
name = "celma_extension"
version = "0.1.0"
authors = ["d-plaindoux <d.plaindoux@free.fr>"]
edition = "2018"

[dependencies]
celma_core  = { version = "0.1.0", path = "../core" }
celma_macro = { version = "0.1.0", path = "../macro" }
