[workspace]
resolver = "2"
members = [
    "lang/v0/core",
    "lang/v0/ast",
    "lang/v0/parser",
    "lang/v0/macro",
    "lang/v1/ast",
    "lang/v1/parser",
    "genlex"
]

[profile.release]
lto = "fat"
codegen-units = 1
