[package]
name = "celma_lang"
version = "0.1.0"
authors = ["dplaindoux <d.plaindoux@fungus.fr>"]
edition = "2018"

[dependencies]
celma_core = { version = "0.1.0", path = "../core" }
proc-macro2 = "0.4.30"
quote = "0.6.12"
syn="0.15.35"
